"""update EnergyConsumption

Revision ID: 2f48be3058e1
Revises: 00c047f712c8
Create Date: 2024-09-16 09:21:55.256834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f48be3058e1'
down_revision: Union[str, None] = '00c047f712c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energy_consumption', sa.Column('carbon_intensity', sa.Float(), nullable=False))
    op.add_column('energy_consumption', sa.Column('datetime', sa.DateTime(timezone=True), nullable=False))
    op.add_column('energy_consumption', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('energy_consumption', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('energy_consumption', 'carbon_footprint_kgco2e',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_unique_constraint('uq_zone_datetime', 'energy_consumption', ['zone', 'datetime'])
    op.drop_column('energy_consumption', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energy_consumption', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint('uq_zone_datetime', 'energy_consumption', type_='unique')
    op.alter_column('energy_consumption', 'carbon_footprint_kgco2e',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('energy_consumption', 'created_at')
    op.drop_column('energy_consumption', 'updated_at')
    op.drop_column('energy_consumption', 'datetime')
    op.drop_column('energy_consumption', 'carbon_intensity')
    # ### end Alembic commands ###
