import os
from dotenv import load_dotenv

# Load .env file
load_dotenv()

# DB settings
POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_HOST = os.getenv("POSTGRES_HOST", "localhost")
POSTGRES_PORT = os.getenv("POSTGRES_PORT", "5432")
POSTGRES_DB = os.getenv("POSTGRES_DB")
SQLALCHEMY_DATABASE_URL = f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"

# ELECTRICITYMAPS API settings
ELECTRICITYMAPS_API_KEY = os.getenv("ELECTRICITYMAPS_API_KEY")
ELECTRICITYMAPS_API_BASE_URL = os.getenv("ELECTRICITYMAPS_API_BASE_URL")
